//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabletcategory1091750
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabletcategory1091750()
        {
            this.Tabletmovie1091750 = new HashSet<Tabletmovie1091750>();
        }
    
        public int fcategoryId { get; set; }
        public string fcategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabletmovie1091750> Tabletmovie1091750 { get; set; }
    }
}
